# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Cameron L Smith
# Description of the Site
description: A personal site for neuroscience, data science, and curiosity
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Neuroscience, Data, Computation, Software
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /PersonalSite/assets/images/transport.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 
facebook_username: 
twitter_username: neuro_cam
instagram_username: PossiblyFractal
linkedin_username: cameronrlsmith
github_username:  Neuro-CS
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Cameron Smith
# URL for the Image of the Author
author-image: https://avatars.githubusercontent.com/u/37383343?v=4
# 60 Words About the Author
author-about: I am Cameron Smith, a PhD candidate at Baylor College of Medicine in the Center for Neuroscience and Artificial Intelligence and Department of Neuroscience. <br><br> I work in the <a href="https://www.bcm.edu/research/faculty-labs/jacob-reimer-lab">Reimer Lab</a> on neuromodulation, big data, and glia. My research looks at the role of astrocytes in alertness and circuit function by leveraging techniques from machine learning and data science. <br><br> I deeply value science outreach, and I regularly talk to high school classes and stream educational content. Feel free to get in touch!
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Neuro-CS

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
